name: Formal Btormc

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup
        run: sed -i "s/%NAME%/test/g" build.sc
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Submodule
        run: git submodule update --init
      - name: Setup BtorMC
        uses: SeddonShen/setup-btormc@v0.0.2
      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.11.5
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: PublishLocal riscv-spec-core
        run: |
          git clone https://github.com/iscas-tis/riscv-spec-core
          cd riscv-spec-core
          git checkout d826f38
          sbt publishLocal -DChiselVersion=3.6.0 -DScalaVersion=2.12.17 -DHashId=true
      - name: mill Test
        run:  mill "chiselModule[3.6.0]".test
      # - name: Single BtorMC Run 15 Steps
      #   if: always()
      #   run: btormc ./test_run_dir/NutCoreFormal_should_pass/NutCore.btor -kmax 15 --trace-gen-full --btor-stats > ./test_run_dir/NutCoreFormal_should_pass/15step.txt
      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Btormc Output Files
          path: test_run_dir/NutCoreFormal_should_pass